!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  D_ang: 0.2
  D_x: 0.8
  D_y: 0.8
  D_z: 0.12
  I_ang: 0.0
  I_x: 0.0
  I_y: 0.0
  I_z: 0.1
  P_ang: 0.15
  P_x: 0.4
  P_y: 0.4
  P_z: 0.35
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      D_ang: 0.2
      D_x: 0.8
      D_y: 0.8
      D_z: 0.12
      I_ang: 0.0
      I_x: 0.0
      I_y: 0.0
      I_z: 0.1
      P_ang: 0.15
      P_x: 0.4
      P_y: 0.4
      P_z: 0.35
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      mult_D_ang: -2
      mult_D_x: 0
      mult_D_y: 0
      mult_D_z: -2
      mult_I_ang: -2
      mult_I_x: -4
      mult_I_y: -4
      mult_I_z: -4
      mult_P_ang: 0
      mult_P_x: 0
      mult_P_y: 0
      mult_P_z: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      running: true
      state: true
      type: ''
    state: []
  mult_D_ang: -2
  mult_D_x: 0
  mult_D_y: 0
  mult_D_z: -2
  mult_I_ang: -2
  mult_I_x: -4
  mult_I_y: -4
  mult_I_z: -4
  mult_P_ang: 0
  mult_P_x: 0
  mult_P_y: 0
  mult_P_z: 0
  running: true
state: []
